version: "3.5"
services: 
  consul: 
    image: consul
    restart: always
    network_mode: host
  registrator: 
    image: gliderlabs/registrator
    restart: always
    network_mode: host
    volumes: 
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    command: "-internal consul://localhost:8500"
